### ISSUE TITLE
Rename lists/items

### ISSUE THREAD

**Issue by airon90** [harr1424/ListMaker#5]
Keep pressed in order to open a menu:
1. Rename (item or list)
2. Delete (item or list)

**Comment by harr1424** [comment]
Thanks for suggesting this, I am getting started on implementing this now.

**Comment by harr1424** [comment]
@airon90 this has been finished, if you would like to test the newest update, check the releases page for the latest APK, otherwise it should become available within the F-Droid client within the next few days. Thanks again for suggesting this feature!
