### ISSUE TITLE
Some accessibility issues in GUIs

### ISSUE THREAD

**Issue by Kazaf123** [harr1424/ListMaker#9]
**Description**
This is a bug report about components that have accessibility issues within the GUI of such an App.
Also, as the following Figure, this report focuses on the content GUI page in the App.
<img width="360" alt="MuMu20221128084014" src="https://user-images.githubusercontent.com/44084361/204169273-a7268ba5-a020-4fe1-ac26-7410691a18cf.png">
**Content**
After I applied my proposed tool to detect the content page, I discovered the following components which have accessibility issues, and I sincerely struggled you could repair these issues so that visually impaired users would use this App more conveniently.
For the buttons named "CANCEL" and "ADD",  could the interval between these two buttons be adjusted to ensure that the visually impaired users do not accidentally touch them?

**Comment by harr1424** [comment]
Thanks for bringing this to my attention.  I've reviewed my source code (see [MainListFragment.kt](https://github.com/harr1424/ListMaker-Android/blob/master/app/src/main/java/com/harr1424/listmaker/UI/MainListFragment.kt) and [DetailListFragment.kt](https://github.com/harr1424/ListMaker-Android/blob/master/app/src/main/java/com/harr1424/listmaker/UI/DetailListFragment.kt) and confirmed that I have implemented the `CANCEL` and `ADD` buttons using `setNegativeButton` and `setPositiveButton` methods of Android's [AlertDialog.Builder](https://developer.android.com/reference/android/app/AlertDialog.Builder) class. 

I do not know of a way to modify how Android implements the spacing or interval between the buttons. These methods are predefined by Android: 
- [setNegativeButton](https://developer.android.com/reference/android/app/AlertDialog.Builder#setNegativeButton(int,%20android.content.DialogInterface.OnClickListener)) used for `CANCEL` 
- [setPositiveButton](https://developer.android.com/reference/android/app/AlertDialog.Builder#setPositiveButton(java.lang.CharSequence,%20android.content.DialogInterface.OnClickListener)) used for `ADD`

The Android Development team strongly suggests developers maintain a high degree of accessibility in their applications, but as described above individual developers do not have control over how these methods actually draw buttons on the GUI. You may consider submitting a similar report [here](https://developer.android.com/about/versions/13/feedback) and referencing this issue. 

Thanks again for taking the time to submit this issue.

**Comment by Kazaf123** [comment]
Thanks for your attention! I got it
